<?php

use Illuminate\Database\Seeder;

class TasksTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run() {
		\DB::table( 'tasks' )->delete();

		\DB::table( 'tasks' )->insert( [
			0  =>
				[
					'id'            => 1,
					'title'         => 'Установите Laravel 5',
					'description'   => null,
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 4,
					'rgt'           => 11,
					'depth'         => 1,
					'created_at'    => '2017-12-29 10:27:33',
					'updated_at'    => '2017-12-29 10:59:33',
				],
			1  =>
				[
					'id'            => 2,
					'title'         => 'Установите Composer',
					'description'   => '<p><a href="https://getcomposer.org" target="_blank">https://getcomposer.org</a></p>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 2,
					'rgt'           => 3,
					'depth'         => 1,
					'created_at'    => '2017-12-29 10:32:20',
					'updated_at'    => '2017-12-29 10:32:42',
				],
			2  =>
				[
					'id'            => 3,
					'title'         => 'Подключите установщик Laravel 5',
					'description'   => '<pre class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; margin-top: 10px; margin-bottom: 20px; background: rgba(238, 238, 238, 0.35); border-radius: 3px; padding: 10px; box-shadow: rgba(0, 0, 0, 0.125) 0px 1px 1px; vertical-align: middle;"><code class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; white-space: pre; word-spacing: normal; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; vertical-align: middle;">composer <span class="token keyword" style="color: rgb(0, 119, 170);">global</span> <span class="token keyword" style="color: rgb(0, 119, 170);">require</span> <span class="token string" style="color: rgb(46, 125, 50);">"laravel/installer"</span></code></pre>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => 1,
					'lft'           => 5,
					'rgt'           => 6,
					'depth'         => 2,
					'created_at'    => '2017-12-29 10:34:26',
					'updated_at'    => '2017-12-29 10:38:34',
				],
			3  =>
				[
					'id'            => 4,
					'title'         => 'Создайте новый Laravel проект',
					'description'   => '<pre class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; margin-top: 10px; margin-bottom: 20px; background: rgba(238, 238, 238, 0.35); border-radius: 3px; padding: 10px; box-shadow: rgba(0, 0, 0, 0.125) 0px 1px 1px; vertical-align: middle;"><code class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; white-space: pre; word-spacing: normal; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; vertical-align: middle;">laravel <span class="token keyword" style="color: rgb(0, 119, 170);">new</span> <span class="token class-name">blog</span></code></pre>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => 1,
					'lft'           => 7,
					'rgt'           => 8,
					'depth'         => 2,
					'created_at'    => '2017-12-29 10:34:53',
					'updated_at'    => '2017-12-29 10:38:34',
				],
			4  =>
				[
					'id'            => 5,
					'title'         => 'Отредактируйте .env файл',
					'description'   => 'Измените значения полей с префиксами DB и APP, указав свои данные для подключения к базе',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => 1,
					'lft'           => 9,
					'rgt'           => 10,
					'depth'         => 2,
					'created_at'    => '2017-12-29 10:38:01',
					'updated_at'    => '2017-12-29 10:38:34',
				],
			5  =>
				[
					'id'            => 6,
					'title'         => 'Создайте контроллер простых страниц',
					'description'   => '<pre class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; margin-top: 10px; margin-bottom: 20px; background: rgba(238, 238, 238, 0.35); border-radius: 3px; padding: 10px; box-shadow: rgba(0, 0, 0, 0.125) 0px 1px 1px; vertical-align: middle;"><code class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; white-space: pre; word-spacing: normal; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; vertical-align: middle;">php artisan make<span class="token punctuation" style="color: rgb(153, 153, 153);">:</span>controller PageController</code></pre>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 12,
					'rgt'           => 13,
					'depth'         => 1,
					'created_at'    => '2017-12-29 10:44:38',
					'updated_at'    => '2017-12-29 10:59:33',
				],
			6  =>
				[
					'id'            => 7,
					'title'         => 'Создайте методы для страниц',
					'description'   => '<p>Для каждой страницы создайте уникальный метод в PageController и роуты для них.</p><pre class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; margin-top: 10px; margin-bottom: 20px; background: rgba(238, 238, 238, 0.35); border-radius: 3px; padding: 10px; box-shadow: rgba(0, 0, 0, 0.125) 0px 1px 1px; vertical-align: middle;"><code class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; white-space: pre; word-spacing: normal; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; vertical-align: middle;"><span class="token scope" style="color: rgb(218, 86, 74);">Route<span class="token punctuation" style="color: rgb(153, 153, 153);">::</span></span><span class="token function" style="color: rgb(85, 85, 85);">get<span class="token punctuation" style="color: rgb(153, 153, 153);">(</span></span><span class="token string" style="color: rgb(46, 125, 50);">\'url\'</span><span class="token punctuation" style="color: rgb(153, 153, 153);">,</span> <span class="token string" style="color: rgb(46, 125, 50);">\'PageController@method\'</span><span class="token punctuation" style="color: rgb(153, 153, 153);">)</span><span class="token punctuation" style="color: rgb(153, 153, 153);">;</span></code></pre>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 14,
					'rgt'           => 15,
					'depth'         => 1,
					'created_at'    => '2017-12-29 10:54:16',
					'updated_at'    => '2017-12-29 10:59:33',
				],
			7  =>
				[
					'id'            => 8,
					'title'         => 'Создайте представления для всех новых методов',
					'description'   => '<p>Создавайте их с расширением .blade.php в папке resources/views</p><p>Каждый метод должен возвращать созданное вами представление с помощью функции&nbsp;</p><pre>view(\'directory.sub_directory.view_name\', [\'foo\' =&gt; \'bar\'])</pre><p>Второй параметр это функции является массивом доступных в представлении переменных (в данном случае только $foo)</p>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 16,
					'rgt'           => 17,
					'depth'         => 1,
					'created_at'    => '2017-12-29 10:59:02',
					'updated_at'    => '2017-12-29 10:59:33',
				],
			8  =>
				[
					'id'            => 9,
					'title'         => 'Создайте общий шаблон для ваших представлений',
					'description'   => '<p>Общая практика называть его layout.blade.php</p><p>Поместите в него весь ваш шаблон кроме содержимого, изменяющегося на страницах.</p>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 18,
					'rgt'           => 19,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:04:13',
					'updated_at'    => '2017-12-29 11:07:50',
				],
			9  =>
				[
					'id'            => 10,
					'title'         => 'Перенесите все ваши страницы в представления',
					'description'   => '<p>Используйте созданный шаблон и директивы</p><pre>@extend(\'layout\')</pre><pre>@section(\'content\')</pre><pre>@yield(\'content\')</pre>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 20,
					'rgt'           => 21,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:07:41',
					'updated_at'    => '2017-12-29 11:07:50',
				],
			10 =>
				[
					'id'            => 11,
					'title'         => 'Установите и настройте Webpack',
					'description'   => null,
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => null,
					'lft'           => 22,
					'rgt'           => 27,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:10:13',
					'updated_at'    => '2017-12-29 11:17:37',
				],
			11 =>
				[
					'id'            => 12,
					'title'         => 'Установите npm пакеты',
					'description'   => '<pre>npm install</pre>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => 11,
					'lft'           => 23,
					'rgt'           => 24,
					'depth'         => 2,
					'created_at'    => '2017-12-29 11:10:31',
					'updated_at'    => '2017-12-29 11:17:37',
				],
			12 =>
				[
					'id'            => 13,
					'title'         => 'Настройте webpack',
					'description'   => '<p>Укажите все необходимые для сборки css и js файлы в webpack.mix.js</p><p>Воспользуйтесь функциями</p><pre>webpack.styles([\'resources/assets/css/foo.css\', \'resources/assets/css/bar.css\'], \'public/css/all.css\');</pre><pre>webpack.scripts([\'resources/assets/js/foo.js\', \'resources/assets/js/bar.js\'], \'public/js/all.js\');</pre><p>В ранее созданном шаблоне подключите файл, используя как ссылку:</p><pre>{{ asset(\'css/all.css\') }}</pre>',
					'done'          => 0,
					'task_group_id' => 1,
					'parent_id'     => 11,
					'lft'           => 25,
					'rgt'           => 26,
					'depth'         => 2,
					'created_at'    => '2017-12-29 11:17:20',
					'updated_at'    => '2017-12-29 11:17:37',
				],
			13 =>
				[
					'id'            => 14,
					'title'         => 'Создайте контроллеры по смыслу и разделите между ними созданные страницы',
					'description'   => 'Не забудьте исправить созданные роуты',
					'done'          => 0,
					'task_group_id' => 2,
					'parent_id'     => null,
					'lft'           => 28,
					'rgt'           => 29,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:22:56',
					'updated_at'    => '2017-12-29 11:30:16',
				],
			14 =>
				[
					'id'            => 15,
					'title'         => 'Для каждой таблицы вашей базы данных создайте миграцию',
					'description'   => '<pre class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; margin-top: 10px; margin-bottom: 20px; background: rgba(238, 238, 238, 0.35); border-radius: 3px; padding: 10px; box-shadow: rgba(0, 0, 0, 0.125) 0px 1px 1px; vertical-align: middle;"><code class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; white-space: pre; word-spacing: normal; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; vertical-align: middle;">php artisan make<span class="token punctuation" style="color: rgb(153, 153, 153);">:</span>migration create_users_table</code></pre>',
					'done'          => 0,
					'task_group_id' => 2,
					'parent_id'     => null,
					'lft'           => 30,
					'rgt'           => 31,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:26:09',
					'updated_at'    => '2017-12-29 11:30:16',
				],
			15 =>
				[
					'id'            => 16,
					'title'         => 'Создайте модели для ваших таблиц',
					'description'   => '<pre class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; margin-top: 10px; margin-bottom: 20px; background: rgba(238, 238, 238, 0.35); border-radius: 3px; padding: 10px; box-shadow: rgba(0, 0, 0, 0.125) 0px 1px 1px; vertical-align: middle;"><code class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; white-space: pre; word-spacing: normal; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; vertical-align: middle;">php artisan make<span class="token punctuation" style="color: rgb(153, 153, 153);">:</span>model User</code></pre>',
					'done'          => 0,
					'task_group_id' => 2,
					'parent_id'     => null,
					'lft'           => 32,
					'rgt'           => 33,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:29:45',
					'updated_at'    => '2017-12-29 11:30:16',
				],
			16 =>
				[
					'id'            => 17,
					'title'         => 'Добавьте в методы контроллеров выборку данных',
					'description'   => 'Замените тестовые данные из предыдущей лабораторной работы на выборку реальных данных из базы, используя созданные модели',
					'done'          => 0,
					'task_group_id' => 2,
					'parent_id'     => null,
					'lft'           => 34,
					'rgt'           => 35,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:34:29',
					'updated_at'    => '2017-12-29 11:42:17',
				],
			17 =>
				[
					'id'            => 18,
					'title'         => 'Реализуйте редактор блога и загрузку сообщений',
					'description'   => 'Применяйте соответствующие HTTP методы',
					'done'          => 0,
					'task_group_id' => 2,
					'parent_id'     => null,
					'lft'           => 38,
					'rgt'           => 39,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:36:31',
					'updated_at'    => '2017-12-29 11:42:17',
				],
			18 =>
				[
					'id'            => 19,
					'title'         => 'Реализуйте авторизацию и регистрацию встроенными средствами Laravel',
					'description'   => '<pre class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; margin-top: 10px; margin-bottom: 20px; background: rgba(238, 238, 238, 0.35); border-radius: 3px; padding: 10px; box-shadow: rgba(0, 0, 0, 0.125) 0px 1px 1px; vertical-align: middle;"><code class=" language-php" style="font-family: &quot;Operator Mono&quot;, &quot;Fira Code&quot;, Consolas, Monaco, &quot;Andale Mono&quot;, monospace; font-size: 11px; white-space: pre; word-spacing: normal; word-break: normal; direction: ltr; color: rgb(0, 0, 0); text-shadow: rgb(255, 255, 255) 0px 1px; line-height: 2; tab-size: 4; hyphens: none; vertical-align: middle;">php artisan make<span class="token punctuation" style="color: rgb(153, 153, 153);">:</span>auth</code></pre>',
					'done'          => 0,
					'task_group_id' => 2,
					'parent_id'     => null,
					'lft'           => 36,
					'rgt'           => 37,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:40:57',
					'updated_at'    => '2017-12-29 11:42:17',
				],
			19 =>
				[
					'id'            => 20,
					'title'         => 'Реализуйте валидацию',
					'description'   => '<p>В каждом методе, принимающем данные от клиента реализуйте валидацию входных данных с помощью метода</p><pre>$this-&gt;validate([\'foo\' =&gt; \'required\'])</pre>',
					'done'          => 0,
					'task_group_id' => 2,
					'parent_id'     => null,
					'lft'           => 40,
					'rgt'           => 41,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:44:39',
					'updated_at'    => '2017-12-29 12:00:31',
				],
			20 =>
				[
					'id'            => 21,
					'title'         => 'Создайте структуру стилей',
					'description'   => '<p>Каждый файл стилей должен отвечать строго за один аспект отображения:</p><ul><li>Шапка</li><li>Подвал</li><li>Элементы формы</li><li>Кнопки</li><li>Отдельные страницы</li></ul><p>Хорошим тоном будет использовать отдельные папки для страниц, блоков и отдельных элементов.</p>',
					'done'          => 0,
					'task_group_id' => 3,
					'parent_id'     => null,
					'lft'           => 42,
					'rgt'           => 43,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:54:01',
					'updated_at'    => '2017-12-29 12:00:31',
				],
			21 =>
				[
					'id'            => 22,
					'title'         => 'Конвертируйте все ваши стили в заданный по варианту диалект',
					'description'   => null,
					'done'          => 0,
					'task_group_id' => 3,
					'parent_id'     => null,
					'lft'           => 44,
					'rgt'           => 49,
					'depth'         => 1,
					'created_at'    => '2017-12-29 11:56:02',
					'updated_at'    => '2017-12-29 12:09:04',
				],
			22 =>
				[
					'id'            => 23,
					'title'         => 'Вынесите стили типографии',
					'description'   => '<p>Все стили, связанные с оформлением текста, шрифты и стандартные размеры кеглей.</p><p>Выделите имена шрифтов и кегли в переменные и используйте их во всех файлах в дальнейшем.</p>',
					'done'          => 0,
					'task_group_id' => 3,
					'parent_id'     => 22,
					'lft'           => 45,
					'rgt'           => 46,
					'depth'         => 2,
					'created_at'    => '2017-12-29 11:59:49',
					'updated_at'    => '2017-12-29 12:00:31',
				],
			23 =>
				[
					'id'            => 24,
					'title'         => 'Воспользуйтесь заданными по варианту возможностями диалекта',
					'description'   => 'Все стили должны максимально использовать возможности диалекта, созданные переменные и др.',
					'done'          => 0,
					'task_group_id' => 3,
					'parent_id'     => 22,
					'lft'           => 47,
					'rgt'           => 48,
					'depth'         => 2,
					'created_at'    => '2017-12-29 12:01:41',
					'updated_at'    => '2017-12-29 12:09:04',
				],
			24 =>
				[
					'id'            => 25,
					'title'         => 'Создайте структуру скриптов',
					'description'   => 'Все js скрипты должны быть разбиты на логичные участки, каждый из которых отвечает за свой функционал/страницу.',
					'done'          => 0,
					'task_group_id' => 4,
					'parent_id'     => null,
					'lft'           => 50,
					'rgt'           => 51,
					'depth'         => 1,
					'created_at'    => '2017-12-29 12:07:54',
					'updated_at'    => '2017-12-29 12:09:04',
				],
			25 =>
				[
					'id'            => 26,
					'title'         => 'Воспользуйтесь модульной архитектурой',
					'description'   => 'Используйте import и require для сборки и подключения модулей в общий файл',
					'done'          => 0,
					'task_group_id' => 4,
					'parent_id'     => null,
					'lft'           => 52,
					'rgt'           => 53,
					'depth'         => 1,
					'created_at'    => '2017-12-29 12:18:12',
					'updated_at'    => '2017-12-29 12:20:34',
				],
			26 =>
				[
					'id'            => 27,
					'title'         => 'Используйте webpack для сборки ES6 исходных файлов',
					'description'   => '<pre>mix.js()</pre>',
					'done'          => 0,
					'task_group_id' => 3,
					'parent_id'     => null,
					'lft'           => 54,
					'rgt'           => 55,
					'depth'         => 1,
					'created_at'    => '2017-12-29 12:19:19',
					'updated_at'    => '2017-12-29 12:20:34',
				],
			27 =>
				[
					'id'            => 28,
					'title'         => 'Реализуйте проверку занятости email при регистрации',
					'description'   => 'Проверка должна производиться на событие onBlur соответствующего поля',
					'done'          => 0,
					'task_group_id' => 5,
					'parent_id'     => null,
					'lft'           => 56,
					'rgt'           => 57,
					'depth'         => 1,
					'created_at'    => '2017-12-29 12:28:18',
					'updated_at'    => '2017-12-29 13:01:39',
				],
			28 =>
				[
					'id'            => 29,
					'title'         => 'Реализуйте добавление комментариев',
					'description'   => 'Форма отправки комментария должна появляться в модальном окне, а данные отправляться с помощью Ajax, данные передаются в формате заданном по варианту.',
					'done'          => 0,
					'task_group_id' => 5,
					'parent_id'     => null,
					'lft'           => 58,
					'rgt'           => 59,
					'depth'         => 1,
					'created_at'    => '2017-12-29 12:40:09',
					'updated_at'    => '2017-12-29 13:01:39',
				],
			29 =>
				[
					'id'            => 30,
					'title'         => 'Реализовать редактирование новостей блога',
					'description'   => '<p>Как и в комментариях форма редактирования&nbsp; появляется в модально окне, но должна быть предзаполнена текущими значениями с использованием дополнительного Ajax-запроса. Отправка данных также осуществляется посредством Ajax по варианту.</p><p>Все ошибки валидации должны обрабатываться и отображаться в форме.</p><p>После завершения запроса запись должна быть обновлена без перезагрузки страницы.</p>',
					'done'          => 0,
					'task_group_id' => 5,
					'parent_id'     => null,
					'lft'           => 60,
					'rgt'           => 61,
					'depth'         => 1,
					'created_at'    => '2017-12-29 13:01:09',
					'updated_at'    => '2017-12-29 13:01:39',
				],
		] );
	}
}